### ISSUE TITLE
Add notifications for nightly build failures

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-plugins#296] opened 2023-08-09 12:34 UTC
## Description
Nightly builds can fail silently without notifying the team, we should add a way either through slack or email integration to let the team know.

Example failure: https://github.com/kedro-org/kedro-plugins/actions/runs/5803202341
Possible solution: https://github.com/slackapi/slack-github-action

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

**Comment by astrojuanlu** [comment] 2023-08-09 13:55
At the moment there are 10/10 apps installed in the Kedro workspace, so new ones can't be added. Happy to chat about this when I'm back.

**Comment by astrojuanlu** [comment] 2023-08-22 11:05
Quick comments: About (1) I didn't know this was possible

![image](https://github.com/kedro-org/kedro-plugins/assets/316517/7e58978d-8d3f-4dbc-a64e-b85cd004ac7d)

(https://github.com/settings/notifications)

About (2) possibly we'd use a non-McK email, such as the one we set up for shared social media accounts

**Comment by SajidAlamQB** [comment] 2023-08-22 13:26
I like approach (1) just using GitHub's built-in functionality is pretty straightforward with not much maintenance required. Plus, we don't need to worry about external dependencies or changes in third-party tools. It puts more of an individual responsibility.

We could make a confluence page guide on how the team can set this up and get everyone who wants to receive notifications from build failures follow it. Additionally it could be a part of our onboarding docs for new engineers on framework.

What do others feel? @noklam @ankatiyar

**Comment by ankatiyar** [comment] 2023-08-22 14:10
I have an idea but I'm not sure how feasible this is - Can lend a hand with figuring it out!
Basically, have a github actions based solution which creates an issue on the `kedro-plugins` repo when there is a nightly build failure? Maybe even configure it to see if there's failures, say 2-3 days in a row? Do you think this is possible @SajidAlamQB @DimedS? We could then bring it into the following sprint.

**Comment by ankatiyar** [comment] 2023-08-22 14:19
Something like this - 
* Move the `schedule:` out of individual `kedro-datasets/airflow/docker/telemetry.yml` workflows. 
* Separate `nightly-build.yml` to call all the tests on the plugins
* job 1: run the test
* job 2: create an issue if there's a failure on job1

**Comment by astrojuanlu** [comment] 2023-08-22 14:20
Dropping this here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

**Comment by SajidAlamQB** [comment] 2023-08-22 15:00
Also what if some failures are intermittent and just need to be re-run. Would that not result in unnecessary issues being made?

**Comment by ankatiyar** [comment] 2023-08-22 15:32
@SajidAlamQB If it's just a weekly build, we can run on Friday and close unnecessary issues on Monday during backlog grooming or sprint planning?

**Comment by merelcht** [comment] 2023-08-31 15:27
I'm not quite sure option 1 here solves the problem. I think that just sends you emails for your own builds that are failing and not for the scheduled nightly builds. I like @ankatiyar 's idea of creating an issue or something else very visible that makes sure we don't miss build failures.

**Comment by astrojuanlu** [comment] 2023-08-31 16:01
Maybe it can be one single issue that gets reopened everytime there's a failure. That way we avoid creating more and more issues that then we need to keep closing. And if the issue is already open and there's a new failure, nothing happens (so it's idempotent). Obviously the first time it would need to be created, and then from there it would look the issue by title, ID, label, or some other mechanims. How does that sound?

**Comment by ankatiyar** [comment] 2023-08-31 16:34
Sounds good @astrojuanlu. Can we park this till I finish the refactoring of the `kedro-plugins` ci?
* https://github.com/kedro-org/kedro-plugins/pull/322
I'm moving stuff around so there might be merge conflicts.

**Closed** 2023-09-04 17:56 UTC
