### ISSUE TITLE
Error Reading a Parquet Dataset as an EagerPolarsDataset in a Kedro Pipeline

### ISSUE THREAD

**Issue by cpinon-grd** [kedro-org/kedro-plugins#500] opened 2023-12-21 12:45 UTC
## Description
Hello! I am encountering an issue when trying to read a Parquet file as an EagerPolarsDataFrame within a Kedro pipeline. My YAML configuration for the dataset is as follows:

```
sessions_preprocessed_pq:
  type: polars.EagerPolarsDataset
  filepath: data/02_intermediate/sessions_preprocessed.parquet
  file_format: parquet
  load_args:
    low_memory: True
```

However, I receive an error.

## Context
This issue arises in a data pipeline where I am attempting to process Parquet files using Polars through Kedro. The error seems to be related to file path normalization or encoding.

## Steps to Reproduce
1. Set up a Kedro pipeline with an EagerPolarsDataset to read a Parquet file.
2. Configure the dataset in YAML with the specified settings.
3. Run the pipeline to load the Parquet file.

## Expected Result
The Parquet file should be loaded into an EagerPolarsDataFrame without any encoding errors.

## Actual Result
The Parquet file should be loaded into an EagerPolarsDataFrame without any encoding errors. The error I get is

```
kedro.io.core.DatasetError: Failed while loading data from data set EagerPolarsDataset(file_format=parquet, filepath=/home/cpinon/Documentos/SecBluRed/SourceCode/kedro/secblured/data/02_intermediate/sessions_preprocessed.parquet, load_args={'low_memory': True}, protocol=file, save_args={}).
'ascii' codec can't decode byte 0xbf in position 1: ordinal not in range(128)

```
located in:

```
/home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/utils/various.py:215 in normalize_filepath

```

```
 /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/util │
│ s/various.py:215 in normalize_filepath                                                           │
│                                                                                                  │
│   212 def normalize_filepath(path: str | Path, *, check_not_directory: bool = True) -> str:      │
│   213 │   """Create a string path, expanding the home directory if present."""                   │
│   214 │   # don't use pathlib here as it modifies slashes (s3:// -> s3:/)                        │
│ ❱ 215 │   path = os.path.expanduser(path)  # noqa: PTH111                                        │
│   216 │   if (                                                                                   │
│   217 │   │   check_not_directory                                                                │
│   218 │   │   and os.path.exists(path)  # noqa: PTH110                                           │
│                                                                                                  │
│ /usr/lib/python3.9/posixpath.py:257 in expanduser                                                │
│                                                                                                  │
│   254 │   │   import pwd                                                                         │
│   255 │   │   name = path[1:i]                                                                   │
│   256 │   │   if isinstance(name, bytes):                                                        │
│ ❱ 257 │   │   │   name = str(name, 'ASCII')                                                      │
│   258 │   │   try:                                                                               │
│   259 │   │   │   pwent = pwd.getpwnam(name)                                                     │
│   260 │   │   except KeyError:            
```
I also must add that my username has no special characters, it is cpinon, so I don't know what is going wrong here.

 When I try to read the same file normally with scan_csv or read_csv in a Jupyter notebook, the file is read correctly, suggesting the issue is specific to the EagerPolarsDataset configuration or handling in Kedro. If I try to use catalog.load("sessions_preprocessed_pq") I get the same error as above indicated.

## Your Environment

Kedro version: 0.19.1
kedro-datasets version: 2.0.0
Python version: 3.9.18
Operating System: Ubuntu 20.04

Thanks in advanve for your time!

**Comment by astrojuanlu** [comment] 2023-12-21 14:21
Hola @cpinon-grd, thanks for reporting.

I see I can reproduce that sort of error with something like:

```
In [14]: os.path.expanduser(b'~_\xbf/Documentos')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[14], line 1
----> 1 os.path.expanduser(b'~_\xbf/Documentos')

File ~/.micromamba/envs/kedro39-dev/lib/python3.9/posixpath.py:257, in expanduser(path)
    255 name = path[1:i]
    256 if isinstance(name, bytes):
--> 257     name = str(name, 'ASCII')
    258 try:
    259     pwent = pwd.getpwnam(name)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 1: ordinal not in range(128)
```

It's unclear to me why a `bytes` object is being passed there. It probably has to do with how we're using fsspec:

https://github.com/kedro-org/kedro-plugins/blob/b9dbce5dc8ccd7e81f0c5f8cdc4167aa0df48435/kedro-datasets/kedro_datasets/polars/eager_polars_dataset.py#L156-L157

Could you share the complete traceback, or at least a few more layers upwards?

**Comment by cpinon-grd** [comment] 2023-12-21 15:03
Sure! The complete traceback is:

```
 /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/kedro/io/co │
│ re.py:186 in load                                                                                │
│                                                                                                  │
│   183 │   │   self._logger.debug("Loading %s", str(self))                                        │
│   184 │   │                                                                                      │
│   185 │   │   try:                                                                               │
│ ❱ 186 │   │   │   return self._load()                                                            │
│   187 │   │   except DatasetError:                                                               │
│   188 │   │   │   raise                                                                          │
│   189 │   │   except Exception as exc:                                                           │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/kedro_datas │
│ ets/polars/eager_polars_dataset.py:157 in _load                                                  │
│                                                                                                  │
│   154 │   │   │   │   " https://pola-rs.github.io/polars/py-polars/html/reference/io.html"       │
│   155 │   │   │   )                                                                              │
│   156 │   │   with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:               │
│ ❱ 157 │   │   │   return load_method(fs_file, **self._load_args)                                 │
│   158 │                                                                                          │
│   159 │   def _save(self, data: pl.DataFrame) -> None:                                           │
│   160 │   │   save_path = get_filepath_str(self._get_save_path(), self._protocol)                │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/io/p │
│ arquet/functions.py:163 in read_parquet                                                          │
│                                                                                                  │
│   160 │   │   │   )                                                                              │
│   161 │                                                                                          │
│   162 │   # For other inputs, defer to `scan_parquet`                                            │
│ ❱ 163 │   lf = scan_parquet(                                                                     │
│   164 │   │   source,                                                                            │
│   165 │   │   n_rows=n_rows,                                                                     │
│   166 │   │   row_count_name=row_count_name,                                                     │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/io/p │
│ arquet/functions.py:303 in scan_parquet                                                          │
│                                                                                                  │
│   300 │   if isinstance(source, (str, Path)):                                                    │
│   301 │   │   source = normalize_filepath(source)                                                │
│   302 │   else:                                                                                  │
│ ❱ 303 │   │   source = [normalize_filepath(source) for source in source]                         │
│   304 │                                                                                          │
│   305 │   return pl.LazyFrame._scan_parquet(                                                     │
│   306 │   │   source,                                                                            │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/io/p │
│ arquet/functions.py:303 in <listcomp>                                                            │
│                                                                                                  │
│   300 │   if isinstance(source, (str, Path)):                                                    │
│   301 │   │   source = normalize_filepath(source)                                                │
│   302 │   else:                                                                                  │
│ ❱ 303 │   │   source = [normalize_filepath(source) for source in source]                         │
│   304 │                                                                                          │
│   305 │   return pl.LazyFrame._scan_parquet(                                                     │
│   306 │   │   source,                                                                            │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/polars/util │
│ s/various.py:215 in normalize_filepath                                                           │
│                                                                                                  │
│   212 def normalize_filepath(path: str | Path, *, check_not_directory: bool = True) -> str:      │
│   213 │   """Create a string path, expanding the home directory if present."""                   │
│   214 │   # don't use pathlib here as it modifies slashes (s3:// -> s3:/)                        │
│ ❱ 215 │   path = os.path.expanduser(path)  # noqa: PTH111                                        │
│   216 │   if (                                                                                   │
│   217 │   │   check_not_directory                                                                │
│   218 │   │   and os.path.exists(path)  # noqa: PTH110                                           │
│                                                                                                  │
│ /usr/lib/python3.9/posixpath.py:257 in expanduser                                                │
│                                                                                                  │
│   254 │   │   import pwd                                                                         │
│   255 │   │   name = path[1:i]                                                                   │
│   256 │   │   if isinstance(name, bytes):                                                        │
│ ❱ 257 │   │   │   name = str(name, 'ASCII')                                                      │
│   258 │   │   try:                                                                               │
│   259 │   │   │   pwent = pwd.getpwnam(name)                                                     │
│   260 │   │   except KeyError:                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 1: ordinal not in range(128)

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 reading_from_catalog = catalog.load("sessions_preprocessed_pq") #load data from Kedro ca     │
│   2                                                                                              │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/kedro/io/da │
│ ta_catalog.py:489 in load                                                                        │
│                                                                                                  │
│   486 │   │   │   extra={"markup": True},                                                        │
│   487 │   │   )                                                                                  │
│   488 │   │                                                                                      │
│ ❱ 489 │   │   result = dataset.load()                                                            │
│   490 │   │                                                                                      │
│   491 │   │   return result                                                                      │
│   492                                                                                            │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/kedro/io/co │
│ re.py:606 in load                                                                                │
│                                                                                                  │
│   603 │   │   return self._filepath / version / self._filepath.name                              │
│   604 │                                                                                          │
│   605 │   def load(self) -> _DO:                                                                 │
│ ❱ 606 │   │   return super().load()                                                              │
│   607 │                                                                                          │
│   608 │   def save(self, data: _DI) -> None:                                                     │
│   609 │   │   self._version_cache.clear()                                                        │
│                                                                                                  │
│ /home/cpinon/Documentos/SecBluRed/SourceCode/kedro/.venv/lib/python3.9/site-packages/kedro/io/co │
│ re.py:195 in load                                                                                │
│                                                                                                  │
│   192 │   │   │   message = (                                                                    │
│   193 │   │   │   │   f"Failed while loading data from data set {str(self)}.\n{str(exc)}"        │
│   194 │   │   │   )                                                                              │
│ ❱ 195 │   │   │   raise DatasetError(message) from exc                                           │
│   196 │                                                                                          │
│   197 │   def save(self, data: _DI) -> None:                                                     │
│   198 │   │   """Saves data by delegation to the provided save method.                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DatasetError: Failed while loading data from data set EagerPolarsDataset(file_format=parquet, 
filepath=/home/cpinon/Documentos/SecBluRed/SourceCode/kedro/secblured/data/02_intermediate/sessions_preprocessed.pa
rquet, load_args={}, protocol=file, save_args={}).
'ascii' codec can't decode byte 0xbf in position 1: ordinal not in range(128)
```

**Comment by astrojuanlu** [comment] 2023-12-21 15:51
Thanks, that's helpful. I cannot reproduce on macOS. Can you try this?

```python
import fsspec
import polars as pl

fs = fsspec.filesystem("file")
with fs.open("/home/cpinon/Documentos/SecBluRed/SourceCode/kedro/secblured/data/02_intermediate/sessions_preprocessed.parquet") as fs_file:
    df = pl.read_parquet(fs_file, low_memory=True)
```

If this works but the Kedro code fails, we'll need to do some deep debugging... 🤞🏽 

If it fails, then the culprit will become more apparent I think.

**Comment by astrojuanlu** [comment] 2023-12-21 15:54
Oh hold on - Polars 0.19 worked for me, but I can reproduce with Polars 0.20 💥 

@cpinon-grd if you want a quick workaround, try downgrading Polars. But we'll have to investigate a bit more what changed. I know Polars is moving away from fsspec so maybe the breakage is intentional.

**Comment by astrojuanlu** [comment] 2023-12-21 15:56
https://github.com/pola-rs/polars/issues/13099

**Comment by astrojuanlu** [comment] 2023-12-21 15:57
This is still a bug in kedro-datasets because our code should work. We either fix the problem, or in the interim we pin the Polars version.

**Comment by cpinon-grd** [comment] 2023-12-22 07:37
Hey, downgrading to polars 0.19 fixed it indeed. Thanks for the quick workaround!

**Comment by astrojuanlu** [comment] 2023-12-23 22:10
This has been fixed upstream, I'm going to close this.

**Closed by astrojuanlu** 2023-12-23 22:10 UTC
Labels: bug, datasets

**Comment by Dekermanjian** [comment] 2024-02-08 20:24
@astrojuanlu thank you so much for the quick response! Downgrading to v0.19 did resolve the issue. Unfortunately, I can not share the file due to Patient Health Information.
